name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and Deploy to Cloud Run
      run: |
        gcloud builds submit --tag gcr.io/$GCP_PROJECT_ID/employee-churn
        gcloud run deploy employee-churn \
          --image gcr.io/$GCP_PROJECT_ID/employee-churn \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
