name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/employee-churn-59343/employee-churn

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy employee-churn \
            --image gcr.io/employee-churn-59343/employee-churn \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
